<?php
/**
 * SerialNumberApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Return (A2X)
 *
 * You can use this service to integrate external applications with customer return processing in SAP S/4HANA Cloud. In every API call, you can make use of the following operations:   - You can retrieve returns orders. Apply any of the filters provided or retrieve all existing data.   - You can create returns orders. Note that you must use “deep insert” requests (a header plus the following entities: header partner, header pricing element, item, item partner, and item pricing element). You cannot create headers without including any related entities.   - For existing returns orders, you can create new items. Note that you must use “deep insert” requests (with the following entities: item partner and item pricing element). You cannot create items without including any related entities.   - For existing returns orders, you can add additional business partners at header and item levels.   - For existing returns orders, you can update the header, header partner, header pricing element, item, item partner, and item pricing element.   - For existing returns orders, you can delete the header, header partner, header pricing element, item, item partner, and item pricing element.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\CustomerReturn\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\CustomerReturn\ApiException;
use BeLenka\SAP\CustomerReturn\Configuration;
use BeLenka\SAP\CustomerReturn\HeaderSelector;
use BeLenka\SAP\CustomerReturn\ObjectSerializer;

/**
 * SerialNumberApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SerialNumberApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet' => [
            'application/json',
        ],
        'aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet' => [
            'application/json',
        ],
        'aCustomerReturnSerialNumberGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet
     *
     * Reads the serial numbers of a specific item.
     *
     * @param  string $customer_return Customer Return (required)
     * @param  string $customer_return_item Customer Return Item (required)
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturn\Model\Wrapper11|\BeLenka\SAP\CustomerReturn\Model\Error
     */
    public function aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet($customer_return, $customer_return_item, $top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'][0])
    {
        list($response) = $this->aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetWithHttpInfo($customer_return, $customer_return_item, $top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);
        return $response;
    }

    /**
     * Operation aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetWithHttpInfo
     *
     * Reads the serial numbers of a specific item.
     *
     * @param  string $customer_return Customer Return (required)
     * @param  string $customer_return_item Customer Return Item (required)
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturn\Model\Wrapper11|\BeLenka\SAP\CustomerReturn\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetWithHttpInfo($customer_return, $customer_return_item, $top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'][0])
    {
        $request = $this->aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetRequest($customer_return, $customer_return_item, $top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturn\Model\Wrapper11' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturn\Model\Wrapper11' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturn\Model\Wrapper11', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturn\Model\Wrapper11';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturn\Model\Wrapper11',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetAsync
     *
     * Reads the serial numbers of a specific item.
     *
     * @param  string $customer_return Customer Return (required)
     * @param  string $customer_return_item Customer Return Item (required)
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetAsync($customer_return, $customer_return_item, $top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'][0])
    {
        return $this->aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetAsyncWithHttpInfo($customer_return, $customer_return_item, $top, $skip, $filter, $inlinecount, $orderby, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetAsyncWithHttpInfo
     *
     * Reads the serial numbers of a specific item.
     *
     * @param  string $customer_return Customer Return (required)
     * @param  string $customer_return_item Customer Return Item (required)
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetAsyncWithHttpInfo($customer_return, $customer_return_item, $top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturn\Model\Wrapper11';
        $request = $this->aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetRequest($customer_return, $customer_return_item, $top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'
     *
     * @param  string $customer_return Customer Return (required)
     * @param  string $customer_return_item Customer Return Item (required)
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGetRequest($customer_return, $customer_return_item, $top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'][0])
    {

        // verify the required parameter 'customer_return' is set
        if ($customer_return === null || (is_array($customer_return) && count($customer_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return when calling aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'
            );
        }
        if (strlen($customer_return) > 10) {
            throw new \InvalidArgumentException('invalid length for "$customer_return" when calling SerialNumberApi.aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'customer_return_item' is set
        if ($customer_return_item === null || (is_array($customer_return_item) && count($customer_return_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return_item when calling aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet'
            );
        }
        if (strlen($customer_return_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$customer_return_item" when calling SerialNumberApi.aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet, must be smaller than or equal to 6.');
        }
        
        if ($top !== null && $top < 0) {
            throw new \InvalidArgumentException('invalid value for "$top" when calling SerialNumberApi.aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet, must be bigger than or equal to 0.');
        }
        
        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling SerialNumberApi.aCustomerReturnItemCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemToSerialNumberGet, must be bigger than or equal to 0.');
        }
        


        
        

        $resourcePath = '/A_CustomerReturnItem(CustomerReturn=\'{CustomerReturn}\',CustomerReturnItem=\'{CustomerReturnItem}\')/to_SerialNumber';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            '$top', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            '$skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $inlinecount,
            '$inlinecount', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            '$orderby', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($customer_return !== null) {
            $resourcePath = str_replace(
                '{' . 'CustomerReturn' . '}',
                ObjectSerializer::toPathValue($customer_return),
                $resourcePath
            );
        }
        // path params
        if ($customer_return_item !== null) {
            $resourcePath = str_replace(
                '{' . 'CustomerReturnItem' . '}',
                ObjectSerializer::toPathValue($customer_return_item),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet
     *
     * Reads a specific serial number.
     *
     * @param  string $customer_return Sales Document (required)
     * @param  string $customer_return_item Sales Document Item (required)
     * @param  string $serial_number Serial Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType|\BeLenka\SAP\CustomerReturn\Model\Error
     */
    public function aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet($customer_return, $customer_return_item, $serial_number, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'][0])
    {
        list($response) = $this->aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetWithHttpInfo($customer_return, $customer_return_item, $serial_number, $select, $contentType);
        return $response;
    }

    /**
     * Operation aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetWithHttpInfo
     *
     * Reads a specific serial number.
     *
     * @param  string $customer_return Sales Document (required)
     * @param  string $customer_return_item Sales Document Item (required)
     * @param  string $serial_number Serial Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType|\BeLenka\SAP\CustomerReturn\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetWithHttpInfo($customer_return, $customer_return_item, $serial_number, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'][0])
    {
        $request = $this->aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetRequest($customer_return, $customer_return_item, $serial_number, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetAsync
     *
     * Reads a specific serial number.
     *
     * @param  string $customer_return Sales Document (required)
     * @param  string $customer_return_item Sales Document Item (required)
     * @param  string $serial_number Serial Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetAsync($customer_return, $customer_return_item, $serial_number, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'][0])
    {
        return $this->aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetAsyncWithHttpInfo($customer_return, $customer_return_item, $serial_number, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetAsyncWithHttpInfo
     *
     * Reads a specific serial number.
     *
     * @param  string $customer_return Sales Document (required)
     * @param  string $customer_return_item Sales Document Item (required)
     * @param  string $serial_number Serial Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetAsyncWithHttpInfo($customer_return, $customer_return_item, $serial_number, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturn\Model\ACustomerReturnSerialNumberType';
        $request = $this->aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetRequest($customer_return, $customer_return_item, $serial_number, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'
     *
     * @param  string $customer_return Sales Document (required)
     * @param  string $customer_return_item Sales Document Item (required)
     * @param  string $serial_number Serial Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGetRequest($customer_return, $customer_return_item, $serial_number, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'][0])
    {

        // verify the required parameter 'customer_return' is set
        if ($customer_return === null || (is_array($customer_return) && count($customer_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return when calling aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'
            );
        }
        if (strlen($customer_return) > 10) {
            throw new \InvalidArgumentException('invalid length for "$customer_return" when calling SerialNumberApi.aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'customer_return_item' is set
        if ($customer_return_item === null || (is_array($customer_return_item) && count($customer_return_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return_item when calling aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'
            );
        }
        if (strlen($customer_return_item) > 6) {
            throw new \InvalidArgumentException('invalid length for "$customer_return_item" when calling SerialNumberApi.aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet, must be smaller than or equal to 6.');
        }
        
        // verify the required parameter 'serial_number' is set
        if ($serial_number === null || (is_array($serial_number) && count($serial_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serial_number when calling aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet'
            );
        }
        if (strlen($serial_number) > 18) {
            throw new \InvalidArgumentException('invalid length for "$serial_number" when calling SerialNumberApi.aCustomerReturnSerialNumberCustomerReturnCustomerReturnCustomerReturnItemCustomerReturnItemSerialNumberSerialNumberGet, must be smaller than or equal to 18.');
        }
        
        

        $resourcePath = '/A_CustomerReturnSerialNumber(CustomerReturn=\'{CustomerReturn}\',CustomerReturnItem=\'{CustomerReturnItem}\',SerialNumber=\'{SerialNumber}\')';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($customer_return !== null) {
            $resourcePath = str_replace(
                '{' . 'CustomerReturn' . '}',
                ObjectSerializer::toPathValue($customer_return),
                $resourcePath
            );
        }
        // path params
        if ($customer_return_item !== null) {
            $resourcePath = str_replace(
                '{' . 'CustomerReturnItem' . '}',
                ObjectSerializer::toPathValue($customer_return_item),
                $resourcePath
            );
        }
        // path params
        if ($serial_number !== null) {
            $resourcePath = str_replace(
                '{' . 'SerialNumber' . '}',
                ObjectSerializer::toPathValue($serial_number),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aCustomerReturnSerialNumberGet
     *
     * Reads all serial numbers.
     *
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturn\Model\Wrapper11|\BeLenka\SAP\CustomerReturn\Model\Error
     */
    public function aCustomerReturnSerialNumberGet($top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberGet'][0])
    {
        list($response) = $this->aCustomerReturnSerialNumberGetWithHttpInfo($top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);
        return $response;
    }

    /**
     * Operation aCustomerReturnSerialNumberGetWithHttpInfo
     *
     * Reads all serial numbers.
     *
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturn\Model\Wrapper11|\BeLenka\SAP\CustomerReturn\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function aCustomerReturnSerialNumberGetWithHttpInfo($top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberGet'][0])
    {
        $request = $this->aCustomerReturnSerialNumberGetRequest($top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturn\Model\Wrapper11' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturn\Model\Wrapper11' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturn\Model\Wrapper11', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturn\Model\Wrapper11';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturn\Model\Wrapper11',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation aCustomerReturnSerialNumberGetAsync
     *
     * Reads all serial numbers.
     *
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnSerialNumberGetAsync($top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberGet'][0])
    {
        return $this->aCustomerReturnSerialNumberGetAsyncWithHttpInfo($top, $skip, $filter, $inlinecount, $orderby, $select, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aCustomerReturnSerialNumberGetAsyncWithHttpInfo
     *
     * Reads all serial numbers.
     *
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aCustomerReturnSerialNumberGetAsyncWithHttpInfo($top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberGet'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturn\Model\Wrapper11';
        $request = $this->aCustomerReturnSerialNumberGetRequest($top, $skip, $filter, $inlinecount, $orderby, $select, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aCustomerReturnSerialNumberGet'
     *
     * @param  int $top Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)
     * @param  string $inlinecount Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['aCustomerReturnSerialNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aCustomerReturnSerialNumberGetRequest($top = null, $skip = null, $filter = null, $inlinecount = null, $orderby = null, $select = null, string $contentType = self::contentTypes['aCustomerReturnSerialNumberGet'][0])
    {

        if ($top !== null && $top < 0) {
            throw new \InvalidArgumentException('invalid value for "$top" when calling SerialNumberApi.aCustomerReturnSerialNumberGet, must be bigger than or equal to 0.');
        }
        
        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling SerialNumberApi.aCustomerReturnSerialNumberGet, must be bigger than or equal to 0.');
        }
        


        
        

        $resourcePath = '/A_CustomerReturnSerialNumber';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            '$top', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            '$skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $inlinecount,
            '$inlinecount', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            '$orderby', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
