<?php
/**
 * ServiceOperationsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customer Return (A2X)
 *
 * You can use this service to integrate external applications with customer return processing in SAP S/4HANA Cloud. In every API call, you can make use of the following operations:   - You can retrieve returns orders. Apply any of the filters provided or retrieve all existing data.   - You can create returns orders. Note that you must use “deep insert” requests (a header plus the following entities: header partner, header pricing element, item, item partner, and item pricing element). You cannot create headers without including any related entities.   - For existing returns orders, you can create new items. Note that you must use “deep insert” requests (with the following entities: item partner and item pricing element). You cannot create items without including any related entities.   - For existing returns orders, you can add additional business partners at header and item levels.   - For existing returns orders, you can update the header, header partner, header pricing element, item, item partner, and item pricing element.   - For existing returns orders, you can delete the header, header partner, header pricing element, item, item partner, and item pricing element.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\CustomerReturn\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\CustomerReturn\ApiException;
use BeLenka\SAP\CustomerReturn\Configuration;
use BeLenka\SAP\CustomerReturn\HeaderSelector;
use BeLenka\SAP\CustomerReturn\ObjectSerializer;

/**
 * ServiceOperationsApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\CustomerReturn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceOperationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'rejectApprovalRequestPost' => [
            'application/json',
        ],
        'releaseApprovalRequestPost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation rejectApprovalRequestPost
     *
     * Rejects a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rejectApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturn\Model\FunctionResult|\BeLenka\SAP\CustomerReturn\Model\Error
     */
    public function rejectApprovalRequestPost($customer_return, string $contentType = self::contentTypes['rejectApprovalRequestPost'][0])
    {
        list($response) = $this->rejectApprovalRequestPostWithHttpInfo($customer_return, $contentType);
        return $response;
    }

    /**
     * Operation rejectApprovalRequestPostWithHttpInfo
     *
     * Rejects a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rejectApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturn\Model\FunctionResult|\BeLenka\SAP\CustomerReturn\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function rejectApprovalRequestPostWithHttpInfo($customer_return, string $contentType = self::contentTypes['rejectApprovalRequestPost'][0])
    {
        $request = $this->rejectApprovalRequestPostRequest($customer_return, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturn\Model\FunctionResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturn\Model\FunctionResult' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturn\Model\FunctionResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturn\Model\FunctionResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturn\Model\FunctionResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation rejectApprovalRequestPostAsync
     *
     * Rejects a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rejectApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rejectApprovalRequestPostAsync($customer_return, string $contentType = self::contentTypes['rejectApprovalRequestPost'][0])
    {
        return $this->rejectApprovalRequestPostAsyncWithHttpInfo($customer_return, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation rejectApprovalRequestPostAsyncWithHttpInfo
     *
     * Rejects a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rejectApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rejectApprovalRequestPostAsyncWithHttpInfo($customer_return, string $contentType = self::contentTypes['rejectApprovalRequestPost'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturn\Model\FunctionResult';
        $request = $this->rejectApprovalRequestPostRequest($customer_return, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'rejectApprovalRequestPost'
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rejectApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function rejectApprovalRequestPostRequest($customer_return, string $contentType = self::contentTypes['rejectApprovalRequestPost'][0])
    {

        // verify the required parameter 'customer_return' is set
        if ($customer_return === null || (is_array($customer_return) && count($customer_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return when calling rejectApprovalRequestPost'
            );
        }
        if (strlen($customer_return) > 13) {
            throw new \InvalidArgumentException('invalid length for "$customer_return" when calling ServiceOperationsApi.rejectApprovalRequestPost, must be smaller than or equal to 13.');
        }
        if (!preg_match("/^'[^']*(''[^']*)*'$/", $customer_return)) {
            throw new \InvalidArgumentException("invalid value for \"customer_return\" when calling ServiceOperationsApi.rejectApprovalRequestPost, must conform to the pattern /^'[^']*(''[^']*)*'$/.");
        }
        

        $resourcePath = '/rejectApprovalRequest';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customer_return,
            'CustomerReturn', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation releaseApprovalRequestPost
     *
     * Approves a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['releaseApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\CustomerReturn\Model\FunctionResult1|\BeLenka\SAP\CustomerReturn\Model\Error
     */
    public function releaseApprovalRequestPost($customer_return, string $contentType = self::contentTypes['releaseApprovalRequestPost'][0])
    {
        list($response) = $this->releaseApprovalRequestPostWithHttpInfo($customer_return, $contentType);
        return $response;
    }

    /**
     * Operation releaseApprovalRequestPostWithHttpInfo
     *
     * Approves a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['releaseApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\CustomerReturn\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\CustomerReturn\Model\FunctionResult1|\BeLenka\SAP\CustomerReturn\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function releaseApprovalRequestPostWithHttpInfo($customer_return, string $contentType = self::contentTypes['releaseApprovalRequestPost'][0])
    {
        $request = $this->releaseApprovalRequestPostRequest($customer_return, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\CustomerReturn\Model\FunctionResult1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\CustomerReturn\Model\FunctionResult1' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\CustomerReturn\Model\FunctionResult1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\CustomerReturn\Model\FunctionResult1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\CustomerReturn\Model\FunctionResult1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation releaseApprovalRequestPostAsync
     *
     * Approves a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['releaseApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function releaseApprovalRequestPostAsync($customer_return, string $contentType = self::contentTypes['releaseApprovalRequestPost'][0])
    {
        return $this->releaseApprovalRequestPostAsyncWithHttpInfo($customer_return, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation releaseApprovalRequestPostAsyncWithHttpInfo
     *
     * Approves a specific returns order.
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['releaseApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function releaseApprovalRequestPostAsyncWithHttpInfo($customer_return, string $contentType = self::contentTypes['releaseApprovalRequestPost'][0])
    {
        $returnType = '\BeLenka\SAP\CustomerReturn\Model\FunctionResult1';
        $request = $this->releaseApprovalRequestPostRequest($customer_return, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'releaseApprovalRequestPost'
     *
     * @param  string $customer_return Value needs to be enclosed in single quotes (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['releaseApprovalRequestPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function releaseApprovalRequestPostRequest($customer_return, string $contentType = self::contentTypes['releaseApprovalRequestPost'][0])
    {

        // verify the required parameter 'customer_return' is set
        if ($customer_return === null || (is_array($customer_return) && count($customer_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_return when calling releaseApprovalRequestPost'
            );
        }
        if (strlen($customer_return) > 13) {
            throw new \InvalidArgumentException('invalid length for "$customer_return" when calling ServiceOperationsApi.releaseApprovalRequestPost, must be smaller than or equal to 13.');
        }
        if (!preg_match("/^'[^']*(''[^']*)*'$/", $customer_return)) {
            throw new \InvalidArgumentException("invalid value for \"customer_return\" when calling ServiceOperationsApi.releaseApprovalRequestPost, must conform to the pattern /^'[^']*(''[^']*)*'$/.");
        }
        

        $resourcePath = '/releaseApprovalRequest';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customer_return,
            'CustomerReturn', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
